specVersion: 0.0.1
description: ''
repository: https://github.com/bifrost-finance/salp-confirm-polkadot-subql.git
schema: ./schema.graphql
network:
  endpoint: wss://rpc.polkadot.io
  # endpoint: wss://polkadot-rpc.testnet2.liebi.com/ws
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 7626626
    mapping:
      handlers:
        - handler: handleBalancesTransfer
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleContributed2
          kind: substrate/EventHandler
          filter:
            module: crowdloan
            method: Contributed