specVersion: 0.0.1
description: ''
repository: https://github.com/bifrost-finance/salp-confirm-polkadot-subql.git
schema: ./schema.graphql
network:
  # endpoint: wss://polkadot.api.onfinality.io/public-ws
  endpoint: wss://bifrost-rpc.testnet.liebi.com/polkadot
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 1
    mapping:
      handlers:
        - handler: handleBalancesTransfer
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleContributed
          kind: substrate/EventHandler
          filter:
            module: crowdloan
            method: Contributed