specVersion: 0.2.0
name: salp-confirm-polkadot-subql
version: 1.0.0
description: ''
repository: https://github.com/bifrost-finance/salp-confirm-polkadot-subql.git
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3'
  endpoint: wss://polkadot-rpc.liebi.com/ws
dataSources:
  - kind: substrate/Runtime
    startBlock: 7626626
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBalancesTransfer
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleContributed
          kind: substrate/EventHandler
          filter:
            module: crowdloan
            method: Contributed
        - handler: handleBatchCompleted
          kind: substrate/EventHandler
          filter:
            module: utility
            method: BatchCompleted
        - handler: handleAllRefunded
          kind: substrate/EventHandler
          filter:
            module: crowdloan
            method: AllRefunded
